[package]
name = "aabb"
version = "0.1.0"
authors = ["Francois Galilee <galilee@google.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ccdd = { version = "0.1.0", registry = "myregistry" }

